Bookstore milestone 2
blackpintz/Bookstore pull request #2
Opened 2021-01-05 13:26 UTC by Bluette1

#### Milestone two
- Prepare the directory structure
  - Create a `components` directory in the src folder for all the presentational components.
  - Create a `containers` directory in the src folder for all the container components.
  - Create an `actions` directory with the index.js file where you’ll define all the Redux actions.
  - Create a `reducers` directory with two files: `books.js` and `index.js`. The former will store the functions responsible for actions on Books, and the latter should combine all the reducers into one. 
 - Implement the App component
  - It should only wrap `BooksList` and `BooksForm` in a `div` selector and display it.
  - Attach this component to render the function in the main `index.js` file.
- Implement the `BooksList` component
  - It should display the books as an `html` table.
  - Each row should contain Book ID, title and category.
  - It should connect to the Redux store and fetch the books from the state.
  - Implement the `Book` component
  - It should accept a `book` object as a `prop`.
  - It should represent a single row in the Books table.
- Implement the BooksForm component
  - It should render a very simple form for adding books. The form should contain a book title input, a select box with categories, and a submit button.
  - Define a constant with a collection containing the book categories: ["Action", "Biography", "History", "Horror", "Kids", "Learning", "Sci-Fi"].
- Define the Redux actions and reducers
  - Implement the `books.js `reducer with `CREATE_BOOK` and REMOVE_BOOK` actions. Remember, your state can not be mutated!
  - Define the `CREATE_BOOK` and `REMOVE_BOOK` actions in `actions/index.js`. They should accept a `book` object as an argument.
- Initialize the Redux store
  - Create the initial state object in `src/index.js`. It may contain just a few books with different titles and categories.
  - Each book in the initial state should have a unique ID. However, we’ll cheat here and implement that functionality by using the `Math.random` function.
  - Render the <App/> component wrapped in `<Provider>` and pass the store down to the components.

2021-01-05 20:28 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @Bluette1 & @blackpintz 👋 
Congratulations on the elaborate done in this milestone. I am glad to see you are getting down to implementing most of the feature required of this milestone. keep it up.

Before we proceed, we have some areas that need addressing first. Kindly check my comments below, 👇  thank you!

## Happy coding 💻 

### Christian Otieno (TSE)

2021-01-05 20:28 UTC, christianotieno commented on src/actions/index.js
> +}
### Optional Change
-  [ ] I would advise against having this block of code here as it does not form part of this actions module.  We can move it to a different module as a helper function to help with the generation of the book id. The best place would be the reducers modules where we would be having our default books already present in the redux store. Also, let's aim to adhere to arrow function syntax of the es6+ as it should now be mandatory for you to use having concluded the module, instead of the normal function declaration in javascript.

2021-01-05 20:28 UTC, christianotieno commented on src/containers/BooksList.js
> +};
## Changes in `BookList` component
- [ ] The book prop has not been validated as is expected. We have an error showing in the console, if I may point out, react is expecting a prop of type string but it is getting an object instead. Arent' we supposed to be wrapping the books we are mapping in the books array inside a recognizable table tag to follow the given hierarchy? 💭 
- [ ] A good inspection of the console should offer us the much-needed clue to this puzzle. let's fix the errors informing in the console to fix these issues in the `BookList` component.

2021-01-06 04:20 UTC, trekab approved these changes
### Approved! :tada: 
Well done team! :+1: You did a great job implementing the requirements for this milestone. Keep up the good work!

_Happy coding!_ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2021-01-06 04:20 UTC, trekab commented on src/containers/BooksList.js
> +  return (
__[Optional]__ Destructure props from the function parameters in functional components to avoid additional variable declarations. (Just like you did for the `Book` component)

2021-01-06 08:17 UTC, merged